spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.zxbtmukdnpjplqjnkogw
spring.datasource.password=8EndC9HvHlZuQvQK
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0
server.compression.enabled=false
spring.mvc.async.request-timeout=5000