spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${AURA_DB_URL}
spring.datasource.username=${AURA_DB_USER}
spring.datasource.password=${AURA_DB_PASS}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.mvc.async.request-timeout=5000
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.address=0.0.0.0
server.compression.enabled=false
