# Nome da aplicação
spring.application.name=backend

# Configuração H2 (Salva em arquivo na pasta /data do projeto)
spring.datasource.url=jdbc:h2:file:./backend/data/auradb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate - Cria as tabelas automaticamente baseado no seu código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2 Console - Permite que você (ou o professor) veja o banco no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Importante para o H2 funcionar com o console aberto
spring.h2.console.settings.web-allow-others=true

# Servidor
server.port=8080
server.address=0.0.0.0
server.compression.enabled=false
